# This script takes in an files and turns each into a
# header and source file with a static byte array with
# that file data.

import os

SOURCE_PREAMBLE = """/** This file is auto generated by headerize_files.py! **/\n"""
NAMESPACE = "sfa"
BYTES_PER_LINE = 12
SOURCE_ASSET_DIR = "src/assets"
HEADER_ASSET_DIR = "include/assets"

def headerize_file(input_file: str, output_file: str, var_name: str):
    os.makedirs(os.path.dirname(f"{HEADER_ASSET_DIR}/{output_file}.hpp"), exist_ok=True)
    os.makedirs(os.path.dirname(f"{SOURCE_ASSET_DIR}/{output_file}.cpp"), exist_ok=True)
    with open(input_file, "rb") as f:
        data = f.read()

        if len(data) == 0:
            print(f"{input_file} is empty!")
            return
        
        with open(f"{HEADER_ASSET_DIR}/{output_file}.hpp", "w") as output:
            output.write(SOURCE_PREAMBLE)
            output.write("#pragma once\n")
            output.write("#include <cstdint>\n")
            output.write("#include <cstddef>\n")
            output.write(f"namespace {NAMESPACE}")
            output.write(" {\n")
            output.write(f"    extern const std::uint8_t {var_name}[];\n")
            output.write(f"    extern const std::size_t {var_name}_size;\n")
            output.write("}\n")
        
        with open(f"{SOURCE_ASSET_DIR}/{output_file}.cpp", "w") as output:
            output.write(SOURCE_PREAMBLE)
            output.write(f"#include \"assets/{output_file}.hpp\"\n")
            output.write(f"namespace {NAMESPACE}")
            output.write(" {\n")
            output.write(f"    const std::uint8_t {var_name}[] = ")
            output.write("{\n")

            for i in range(0, len(data), BYTES_PER_LINE):
                chunk = data[i:i+BYTES_PER_LINE]
                hexes = ", ".join(f"0x{b:02X}" for b in chunk)
                output.write(f"        {hexes},\n")
            output.write("    };\n")
            
            output.write(f"    const std::size_t {var_name}_size = sizeof({var_name});\n")

            output.write("}\n")

if __name__ == '__main__':
    headerize_file("assets/sprites/test_image.png", "sprites/test_image", "test_image")